# Generated by Django 2.0.6 on 2018-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_nm', models.CharField(max_length=30)),
                ('repo_name', models.CharField(max_length=250)),
                ('branch_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CommitInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=250)),
                ('branch_name', models.CharField(max_length=30)),
                ('commit_message', models.CharField(max_length=250)),
                ('commit_url', models.URLField()),
                ('commit_author', models.CharField(max_length=30)),
                ('commit_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_nm', models.CharField(max_length=30)),
                ('repo_name', models.CharField(max_length=250)),
                ('repo_url', models.URLField()),
                ('repo_language', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlrFlg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_nm', models.CharField(max_length=30)),
                ('local_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_nm', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=250)),
                ('public_gists_count', models.PositiveIntegerField()),
                ('public_repos_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
