# Generated by Django 2.0.6 on 2018-06-19 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_url', models.URLField()),
                ('commit_owner', models.CharField(max_length=30)),
                ('commit_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.PositiveIntegerField()),
                ('repo_name', models.CharField(max_length=250)),
                ('repo_url', models.URLField()),
                ('repo_language', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollerFollng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_foller_follng', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_nm', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=250)),
                ('public_gists_count', models.PositiveIntegerField()),
                ('public_repos_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
